# Generated by Django 4.2.3 on 2023-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0006_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='updatet_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(help_text='Отьметьте, если торг уместен', verbose_name='Торг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
    ]
